name: CI Pipeline

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Dependencies
        working-directory: app_python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint Code
        working-directory: app_python
        run: flake8 .

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Dependencies
        working-directory: app_python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        working-directory: app_python
        run: pytest

  snyk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Snyk CLI
        run: |
          npm install -g snyk
      - name: Run Snyk Vulnerability Test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }} 
        run: snyk test --all-projects 

  docker:
    needs: [lint, test, snyk]  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: app_python
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-fastapi-app:latest
